baseURL: "https://bakicakici.eu/" 
title: Baki Cakici
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: writing
          url: writing/
          weight: 5 
        - name: teaching
          url: teaching/
          weight: 2
        - name: things
          url: things/
          weight: 3
        - name: about
          url: about/
          weight: 4

params:
    description: "Associate professor in STS/sociology/computer science at the IT University of Copenhagen."
    author: Baki Cakici
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["writing","teaching","things","about"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Baki Cakici
          subtitle: "I am an associate professor working at the intersections of science & technology studies (STS), sociology, and computer science at the [IT University of Copenhagen](https://itu.dk/). My research interests include the politics of data, software studies, and identification systems."
          # imageUrl: "picture.jpeg"
          # imageWidth: 160
          # imageHeight: 160
          buttons:
            - name: writing
              url: writing/
            - name: teaching
              url: teaching/
            - name: things
              url: things/
            - name: about/
              url: about/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/

    socialIcons:
        - name: Email
          url: mailto:mail@bakicakici.eu
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=0UVuv_0AAAAJ
        - name: GitHub
          url: https://github.com/bakicakici
          
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Baki Cakici"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
